# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Build tools
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      build-tools:
        patterns:
          - "vite"
          - "vite-plugin-dts"
          - "@vitejs/plugin-vue"
          - "typescript"
          - "vue-tsc"

  # Testing tools
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      test-tools:
        patterns:
          - "vitest"
          - "@vue/test-utils"
          - "happy-dom"

  # Documentation tools
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      docs-tools:
        patterns:
          - "vitepress"
          - "typedoc"
          - "typedoc-plugin-markdown"
          - "typedoc-vitepress-theme"

  # Linting and code quality
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      linting:
        patterns:
          - "eslint"
          - "@kitbag/eslint-config"
          - "globals"
