import { CreatedRouteOptions, Route, RouteDataOf, Routes } from '@/types/route'
import { LastInArray } from '@/types/utilities'
import { ExtractRouteStateParamsAsOptional } from '@/types/state'
import { UrlString } from '@/types/urlString'
import { UrlParamsReading } from '@/types/url'
import { GetTitleCallback } from '@/types/routeTitle'

/**
 * The match a route resolved to, which is the last of its matches. Falls back to the wide match type when
 * the matches are not a concrete tuple, so an unregistered router stays assignable.
 */
export const IS_RESOLVED_ROUTE_SYMBOL = Symbol('IS_RESOLVED_ROUTE_SYMBOL')

/**
 * A type guard for determining if a value is a ResolvedRoute.
 * @param value - The value to check.
 * @returns `true` if the value is a ResolvedRoute, otherwise `false`.
 * @group Type Guards
 */
export function isResolvedRoute(value: unknown): value is ResolvedRoute {
  return typeof value === 'object' && value !== null && IS_RESOLVED_ROUTE_SYMBOL in value
}

export type ResolvedRouteInternal = {
  [IS_RESOLVED_ROUTE_SYMBOL]: true,
}

type MatchedRoute<TMatches> = LastInArray<TMatches, CreatedRouteOptions> extends infer TMatched
  ? unknown extends TMatched ? CreatedRouteOptions : TMatched
  : never

/**
 * Represents a route that the router has matched to current browser location.
 * @template TRoute - Underlying Route that has been resolved.
 */
export type ResolvedRoute<TRoute extends Route = Route> = Readonly<{
  /**
   * Unique identifier for the route, generated by router.
  */
  id: TRoute['id'],
  /**
   * The specific route properties that were matched in the current route.
  */
  matched: MatchedRoute<TRoute['matches']>,
  /**
   * The specific route properties that were matched in the current route, including any ancestors.
   * Order of routes will be from greatest ancestor to narrowest matched.
  */
  matches: TRoute['matches'],
  /**
   * Unique identifier for the route. Name is used for routing and for matching.
  */
  name: TRoute['name'],
  /**
   * Key value pair for route params, values will be the user provided value from current browser location.
  */
  params: UrlParamsReading<TRoute>,
  /**
   * Type for additional data intended to be stored in history state.
   */
  state: ExtractRouteStateParamsAsOptional<TRoute['state']>,
  /**
   * String value of the resolved URL. When the route was matched through an alias this is the alias url,
   * so navigating to it again stays where the user is.
   */
  href: UrlString,
  /**
   * String value of the route's own URL, built from its path and the resolved params. The same as `href`
   * unless the route was matched through an alias.
   */
  canonical: UrlString,
  /**
   * Query value of the route.
   */
  query: URLSearchParams,
  /**
   * Hash value of the route.
   */
  hash: string,
  /**
   * Returns the title of the route from its `setTitle` callback, or from the closest parent route that
   * defines one.
   */
  getTitle: GetTitleCallback,
}>

/**
 * A resolved route whose loaders' data is available. Only the route being navigated to has data: a route
 * the router merely resolved is not being loaded, so data on it could never settle. The current route and
 * a props getter's route have it, `router.resolve` and hooks do not.
 */
export type WithData<TRoute extends Route = Route> = {
  /**
   * What the route's loaders resolve to, keyed by loader name. A route whose only loader is unnamed
   * exposes that loader's data here directly. Always promises, since loaders never block rendering.
   */
  data: RouteDataOf<TRoute['matches']>,
}

/**
 * This type is the same as `ResolvedRoute<TRoutes[number]>` while remaining distributive
 */
export type RouterResolvedRouteUnion<TRoutes extends Routes> = {
  [K in keyof TRoutes]: ResolvedRoute<TRoutes[K]>
}[number]

/**
 * Converts a union of Route types to a union of ResolvedRoute types while preserving the discriminated union structure for narrowing.
 * This is useful when you have a Route union (like `TRoutes[number]`) and need it to narrow properly.
 * Uses a distributive conditional type to ensure unions are properly distributed.
 *
 * @example
 * type RouteUnion = RouteA | RouteB
 * type ResolvedUnion = ResolvedRouteUnion<RouteUnion> // ResolvedRoute<RouteA> | ResolvedRoute<RouteB>
 */
export type ResolvedRouteUnion<TRoute extends Route> = TRoute extends Route
  ? ResolvedRoute<TRoute>
  : never
