import { Param } from '@/types/paramTypes'
import { PrefetchConfig } from '@/types/prefetch'
import { RouteMeta } from '@/types/register'
import { LastInArray } from '@/types/utilities'
import { CreateRouteOptions } from '@/types/createRouteOptions'
import { RouteContext } from '@/types/routeContext'
import { Url } from '@/types/url'
import { GetRouteTitle } from '@/types/routeTitle'
import { Hooks } from '@/models/hooks'
import { RouteRedirect } from './redirects'
import { RouteViews } from '@/types/routeViews'

export const IS_ROUTE_SYMBOL = Symbol('IS_ROUTE_SYMBOL')

export function isRoute(value: unknown): value is Route & RouteInternal {
  return typeof value === 'object' && value !== null && IS_ROUTE_SYMBOL in value
}

export type RouteInternal = {
  [IS_ROUTE_SYMBOL]: true,
  depth: number,
  hooks: Hooks[],
  redirect: RouteRedirect,
  getTitle: GetRouteTitle,
}

/**
 * Represents an immutable array of Route instances. Return value of `createRoute`, expected param for `createRouter`.
 */
export type Routes = readonly Route[]

/**
 * The Route properties originally provided to `createRoute`, a pure snapshot of the options. Components
 * and prop getters do not live here — they live on `route.views` (see {@link RouteViews}).
 */
export type CreatedRouteOptions = Omit<CreateRouteOptions, 'component' | 'components'> & {
  id: string,
}
/**
 * Represents the structure of a route within the application. Return value of `createRoute`
 * @template TName - Represents the unique name identifying the route, typically a string.
 * @template TPath - The type or structure of the route's path.
 * @template TQuery - The type or structure of the query parameters associated with the route.
 */
export type Route<
  TName extends string = string,
  TUrl extends Url = Url,
  TMeta extends RouteMeta = RouteMeta,
  TState extends Record<string, Param> = Record<string, Param>,
  TMatches extends CreatedRouteOptions[] = CreatedRouteOptions[],
  TContext extends RouteContext[] = RouteContext[],
  TViews extends RouteViews[] = RouteViews[]
> = TUrl & {
  /**
   * Unique identifier for the route, generated by router.
  */
  id: string,
  /**
   * The specific route properties that were matched in the current route.
  */
  matched: LastInArray<TMatches, CreatedRouteOptions>,
  /**
   * The specific route properties that were matched in the current route, including any ancestors.
   * Order of routes will be from greatest ancestor to narrowest matched.
  */
  matches: TMatches,
  /**
   * The components and prop getters for the route and its ancestors, indexed by depth (parallel to
   * `matches`). Each entry holds the components and prop getters added for that route.
  */
  views: TViews,
  /**
   * Identifier for the route as defined by user. Name must be unique among named routes. Name is used for routing and for matching.
  */
  name: TName,
  /**
   * Represents additional metadata associated with a route, combined with any parents.
  */
  meta: TMeta,
  /**
   * Represents the schema of the route state, combined with any parents.
  */
  state: TState,
  /**
   * Determines what assets are prefetched when router-link is rendered for this route. Overrides router level prefetch.
  */
  prefetch?: PrefetchConfig,
  /**
   * Related routes and rejections for the route. The context is exposed to the hooks and props callback functions for this route.
   */
  context: TContext,
}

export type GenericRoute = Url & {
  id: string,
  name: string,
  matched: CreatedRouteOptions,
  matches: CreatedRouteOptions[],
  views: RouteViews[],
  meta: RouteMeta,
  state: Record<string, Param>,
  prefetch?: PrefetchConfig,
}
