import { RouteUpdate } from '@/types/routeUpdate'
import { ResolvedRoute } from '@/types/resolved'
import { RouteDataOf } from '@/types/route'
import { QuerySource } from '@/types/querySource'

export type RouterRoute<TRoute extends ResolvedRoute = ResolvedRoute> = {
  /**
   * Unique identifier for the route, generated by router.
   */
  readonly id: TRoute['id'],
  /**
   * Identifier for the route as defined by user. Name must be unique among named routes. Name is used for routing and for matching.
   */
  readonly name: TRoute['name'],
  /**
   * The specific route properties that were matched in the current route.
   */
  readonly matched: TRoute['matched'],
  /**
   * The specific route properties that were matched in the current route, including any ancestors.
   * Order of routes will be from greatest ancestor to narrowest matched.
   */
  readonly matches: TRoute['matches'],
  /**
   * Hash value of the route.
   */
  readonly hash: string,
  /**
   * Update the route.
   */
  readonly update: RouteUpdate<TRoute>,
  /**
   * String value of the resolved URL. When the route was matched through an alias this is the alias url.
   */
  readonly href: TRoute['href'],
  /**
   * String value of the route's own URL. The same as `href` unless the route was matched through an alias.
   */
  readonly canonical: TRoute['canonical'],
  /**
   * Title of the route.
   */
  readonly getTitle: TRoute['getTitle'],
  /**
   * What the route's loaders resolve to, keyed by loader name. A route whose only loader is unnamed
   * exposes that loader's data here directly.
   */
  readonly data: RouteDataOf<TRoute['matches']>,

  params: TRoute['params'],
  state: TRoute['state'],

  get query(): URLSearchParams,
  set query(value: QuerySource),
}
