import { RouteUpdate } from '@/types/routeUpdate'
import { ResolvedRoute } from '@/types/resolved'
import { QuerySource } from '@/types/querySource'

export type RouterRoute<TRoute extends ResolvedRoute = ResolvedRoute> = {
  /**
   * Unique identifier for the route, generated by router.
   */
  readonly id: TRoute['id'],
  /**
   * Identifier for the route as defined by user. Name must be unique among named routes. Name is used for routing and for matching.
   */
  readonly name: TRoute['name'],
  /**
   * The specific route properties that were matched in the current route.
   */
  readonly matched: TRoute['matched'],
  /**
   * The specific route properties that were matched in the current route, including any ancestors.
   * Order of routes will be from greatest ancestor to narrowest matched.
   */
  readonly matches: TRoute['matches'],
  /**
   * The stores for routes including ancestors.
   * @internal
   */
  readonly hooks: TRoute['hooks'],
  /**
   * Hash value of the route.
   */
  readonly hash: TRoute['hash'],
  /**
   * Update the route.
   */
  readonly update: RouteUpdate<TRoute>,
  /**
   * String value of the resolved URL.
   */
  readonly href: TRoute['href'],

  params: TRoute['params'],
  state: TRoute['state'],

  get query(): URLSearchParams,
  set query(value: QuerySource),
}
